Repository boostcampwm-2021/WEB23-HyupUp, pull requests merged in 2021-11, with the labels that each got.

#43 feat: user api 예시 코드 추가 [#13]
  server/app.ts
  server/src/Users/Users.controller.ts
  server/src/Users/Users.router.ts
Labels: 🎯 환경설정

#45 feat: landing page 작성 [#44]
  client/src/pages/LandingPage.tsx
Labels: 🎯 홈페이지

#48 공통 컴포넌트 모달 구현
  client/src/lib/design/Modal/index.tsx
  client/src/styles/theme.ts
Labels: 🎯 환경설정, 😎 front-end, 🖋 리뷰요청

#49 공통 컴포넌트 버튼 제작
  client/src/lib/design/Button.tsx
Labels: 🎯 환경설정, 😎 front-end, 🖋 리뷰요청

#56 작업 페이지에서 사용할 api와 전역 변수 작성
  client/src/components/SideBarDropDown.tsx
  client/src/contexts/epicContext.tsx
  client/src/contexts/storyContext.tsx
  client/src/lib/hooks/useContextHooks.ts
  server/app.ts
  server/lib/corsConfig.ts
  server/package.json
  server/src/Epics/Epics.controller.ts
  server/src/Epics/Epics.router.ts
  server/src/Projects/Projects.controller.ts
  server/src/Projects/Projects.entity.ts
  server/src/Projects/Projects.router.ts
  server/src/Stories/Stories.controller.ts
  server/src/Stories/Stories.entity.ts
  server/src/Stories/Stories.router.ts
  server/src/Tasks/Tasks.controller.ts
  server/src/Tasks/Tasks.entity.ts
  server/src/Tasks/Tasks.router.ts
  server/src/Users/Users.entity.ts
  yarn.lock
Labels: 🎯 작업 페이지, 😎 front-end, 😇 back-end

#59 Workpage 에 Header 컴포넌트 추가
  client/src/components/Roadmap/style.ts
  client/src/components/SideBar/style.ts
  client/src/lib/common/Header/style.ts
  client/src/pages/WorkPage.tsx
Labels: 🎯 작업 페이지

#62 할 일을 입력하는 컴포넌트 만들기
  client/package.json
  client/src/components/SideBar/SideBarDropDown.tsx
  client/src/components/SideBar/index.tsx
  client/src/components/SideBarDropDown.tsx
  client/src/components/TodoInputBar/index.tsx
  client/src/components/TodoInputBar/style.ts
  client/src/contexts/epicContext.tsx
  client/src/contexts/storyContext.tsx
  client/src/contexts/userContext.tsx
  client/src/lib/api/project.ts
  client/src/lib/api/todo.ts
  client/src/lib/design/DropDown.tsx
  client/src/pages/MainPage.tsx
  server/app.ts
  server/lib/requestVaildator.ts
  server/src/Epics/Epics.controller.ts
  server/src/Projects/Projects.controller.ts
  server/src/Stories/Stories.controller.ts
  server/src/Tasks/Tasks.entity.ts
  server/src/Todo/Todo.controller.ts
  server/src/Todo/Todo.entity.ts
  server/src/Todo/Todo.router.ts
  yarn.lock
Labels: 🎯 홈페이지, 😎 front-end, 😇 back-end, 🖋 리뷰요청

#66 수정된 StoryContext 기반 칸반 렌더링
  client/src/components/KanbanTodo/index.tsx
Labels: 🎯 칸반보드

#63 user의 개인 할일과 팀에서 할일을 받아오도록 api 추가 및 context 수정
  client/src/contexts/userContext.tsx
  server/app.ts
  server/src/Tasks/Tasks.entity.ts
  server/src/Todo/Todo.entity.ts
  server/src/Users/Users.controller.ts
  server/src/Users/Users.service.ts
Labels: 🎯 홈페이지, 😇 back-end, 🖋 리뷰요청

#65 추가버튼을 눌러 에픽을 추가할 수 있다.
  client/src/components/EpicPlaceholder/index.tsx
  client/src/components/EpicPlaceholder/style.ts
  client/src/components/Roadmap/index.tsx
  client/src/components/Roadmap/style.ts
  client/src/components/SideBar/index.tsx
  client/src/lib/api/epic.ts
  client/src/pages/WorkPage.tsx
  server/src/Epics/Epics.controller.ts
  server/src/Epics/Epics.router.ts
  server/src/Epics/Epics.sql
Labels: 🎯 로드맵, 😎 front-end, 😇 back-end, 🖋 리뷰요청

#73 메인 페이지 리스트 뷰 구현
  client/src/components/ListViewLayer/ListView/index.tsx
  client/src/components/ListViewLayer/ListView/style.ts
  client/src/components/ListViewLayer/ListViewHeader/index.tsx
  client/src/components/ListViewLayer/ListViewHeader/style.ts
  client/src/components/ListViewLayer/ListViewItem/index.tsx
  client/src/components/TodoInputBar/style.ts
  client/src/contexts/userContext.tsx
  client/src/pages/MainPage.tsx
  server/src/Users/Users.service.ts
Labels: 🎯 홈페이지, 😎 front-end

#76 메인페이지 리스트뷰 구현
  client/src/components/ListViewLayer/ListView/index.tsx
  client/src/components/ListViewLayer/ListView/style.ts
  client/src/components/ListViewLayer/ListViewHeader/index.tsx
  client/src/components/ListViewLayer/ListViewHeader/style.ts
  client/src/components/ListViewLayer/ListViewItem/index.tsx
  client/src/components/ListViewLayer/ListViewItem/style.ts
  client/src/components/TodoInputBar/index.tsx
  client/src/components/TodoInputBar/style.ts
  client/src/contexts/userContext.tsx
  client/src/lib/api/todo.ts
  client/src/lib/design/Button.tsx
  client/src/pages/MainPage.tsx
  client/src/styles/GlobalStyle.ts
  server/src/Todo/Todo.controller.ts
  server/src/Users/Users.service.ts
Labels: 🎯 홈페이지, 😎 front-end, 😇 back-end, 🖋 리뷰요청, 🧐 refactor

#75 Post 요청을 통해 스토리 아이템을 추가할 수 있으며, 기존 스토리 아이템을 가져올 수 있다
  client/src/components/KanbanTodo/index.tsx
  client/src/contexts/storyContext.tsx
  client/src/lib/api/story.ts
  server/src/Stories/Stories.controller.ts
  server/src/Stories/Stories.router.ts
Labels: 🎯 칸반보드, 😎 front-end

#102 컴포넌트 레이어 구조 분리, 프론트엔드 타입 선언
  client/src/components/KanbanTodo/index.tsx
  client/src/components/ListViewHeader/index.tsx
  client/src/components/ListViewHeader/style.ts
  client/src/components/ListViewItem/index.tsx
  client/src/components/ListViewItem/style.ts
  client/src/components/Profile/index.tsx
  client/src/components/Profile/style.ts
  client/src/components/SideBarDropdown/index.tsx
  client/src/components/SideBarDropdown/style.ts
  client/src/contexts/epicContext.tsx
  client/src/contexts/storyContext.tsx
  client/src/contexts/userContext.tsx
  client/src/layers/Backlog/index.tsx
  client/src/layers/Header/index.tsx
  client/src/layers/Header/style.ts
  client/src/layers/Kanban/index.tsx
  client/src/layers/Kanban/style.ts
  client/src/layers/ListView/index.tsx
  client/src/layers/ListView/style.ts
  client/src/layers/Roadmap/index.tsx
  client/src/layers/Roadmap/style.ts
  client/src/layers/SideBar/index.tsx
  client/src/layers/SideBar/style.ts
  client/src/lib/api/epic.ts
  client/src/lib/api/story.ts
  client/src/pages/MainPage.tsx
  client/src/pages/WorkPage.tsx
  client/src/types/epic.d.ts
  client/src/types/project.d.ts
  client/src/types/story.d.ts
  client/src/types/task.d.ts
Labels: 🧐 refactor

#104 동료의 상태를 확인할 수 있는 상태창 작성
  client/public/icons/chevron-down.svg
  client/public/icons/group.svg
  client/src/components/BackLogItem/index.tsx
  client/src/components/BackLogItem/style.ts
  client/src/components/CoworkerStatus/avator.tsx
  client/src/components/CoworkerStatus/index.tsx
  client/src/components/CoworkerStatus/style.ts
  client/src/components/CoworkerStatusItem/Avatar/index.tsx
  client/src/components/CoworkerStatusItem/Avatar/style.ts
  client/src/components/CoworkerStatusItem/StatusTitle/index.tsx
  client/src/components/CoworkerStatusItem/StatusTitle/style.ts
  client/src/components/SideBarDropdown/index.tsx
  client/src/layers/Backlog/index.tsx
  client/src/layers/Backlog/style.ts
  client/src/layers/CoworkerStatus/index.tsx
  client/src/layers/CoworkerStatus/style.ts
  client/src/lib/api/user.ts
  client/src/lib/design/DropDown/index.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/WorkPage.tsx
  server/app.ts
  server/package.json
  server/socket.ts
  server/src/Epics/Epics.router.ts
  server/src/Projects/Projects.router.ts
  server/src/Stories/Stories.router.ts
  server/src/Tasks/Tasks.controller.ts
  server/src/Tasks/Tasks.router.ts
  server/src/Users/Users.controller.ts
  server/src/Users/Users.router.ts
Labels: 🎯 홈페이지, 🎯 백로그, 😎 front-end, 😇 back-end, 🖋 리뷰요청

#107 Story 의 이름을 수정하면 Focus 가 사라지면 API 호출 및 Reducer 함수를 호출한다
  client/src/components/CoworkerStatus/index.tsx
  client/src/components/KanbanItem/index.tsx
  client/src/components/KanbanTodo/index.tsx
  client/src/components/KanbanTodo/style.ts
  client/src/components/Profile/index.tsx
  client/src/components/SideBarDropdown/index.tsx
  client/src/components/index.ts
  client/src/layers/Kanban/index.tsx
  client/src/layers/index.ts
  client/src/lib/api/story.ts
  client/src/lib/common/index.ts
  client/src/lib/hooks/useInput.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/WorkPage/index.tsx
  client/src/pages/index.ts
  client/src/types/story.d.ts
  server/src/Stories/Stories.controller.ts
  server/src/Stories/Stories.router.ts
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end, 😊 database

#105 에픽 관련 소켓로직 작성 및 로드맵 컴포넌트 구현
  client/src/components/EpicPlaceholder/index.test.tsx
  client/src/components/EpicPlaceholder/index.tsx
  client/src/components/RoadmapCalendar/index.tsx
  client/src/components/RoadmapCalendar/style.ts
  client/src/contexts/epicContext.tsx
  client/src/layers/Roadmap/index.tsx
  client/src/layers/Roadmap/style.ts
  client/src/lib/api/epic.ts
  client/src/lib/api/project.ts
  client/src/lib/api/story.ts
  client/src/lib/api/todo.ts
  client/src/lib/api/user.ts
  client/src/lib/common/message/error.ts
  client/src/lib/common/message/index.ts
  client/src/lib/common/message/success.ts
  client/src/lib/hooks/index.ts
  client/src/lib/hooks/useSocketReceive.tsx
  client/src/lib/utils/date.ts
  client/src/pages/WorkPage/index.tsx
  client/src/setupTests.ts
  client/src/types/epic.d.ts
  client/src/types/epic.ts
  mock.sql
  server/lib/types/index.d.ts
  server/lib/types/req-body.d.ts
  server/socket.ts
Labels: 🎯 로드맵, 😎 front-end, 😇 back-end, 🖋 리뷰요청

#111 삭제 확인 모달을 통한 스토리 삭제 기능 구현
  client/src/components/KanbanItem/index.tsx
  client/src/components/KanbanItem/style.ts
  client/src/components/KanbanTodo/index.tsx
  client/src/components/KanbanTodo/style.ts
  client/src/contexts/storyContext.tsx
  client/src/lib/api/story.ts
  client/src/lib/design/Modal/index.tsx
  server/src/Stories/Stories.controller.ts
  server/src/Stories/Stories.router.ts
  yarn.lock
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end

#109 TODO , TASK api 로직 작성 및 연결 | 메인페이지 리팩토링
  client/public/icons/personal-icon.svg
  client/public/icons/project-icon.svg
  client/src/components/ListViewItem/index.tsx
  client/src/components/ListViewItem/style.ts
  client/src/components/Profile/index.tsx
  client/src/components/Profile/style.ts
  client/src/contexts/userContext.tsx
  client/src/layers/Header/index.tsx
  client/src/layers/ListView/index.tsx
  client/src/lib/api/task.ts
  client/src/lib/api/todo.ts
  client/src/lib/common/message/error.ts
  client/src/lib/hooks/useContextHooks.tsx
  server/src/Tasks/Tasks.controller.ts
  server/src/Tasks/Tasks.router.ts
  server/src/Todo/Todo.controller.ts
  server/src/Todo/Todo.router.ts
  server/src/Users/Users.controller.ts
Labels: 🎯 홈페이지, 😎 front-end, 😇 back-end, 😱 bug, 🖋 리뷰요청, 🧐 refactor

#116 user 상태 Recoil로 마이그레이션
  client/package.json
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/ListViewItem/index.tsx
  client/src/components/TodoInputBar/index.tsx
  client/src/layers/CoworkerStatus/index.tsx
  client/src/layers/ListView/index.tsx
  client/src/lib/utils/sort.ts
  client/src/pages/LandingPage/index.tsx
  client/src/recoil/user/atom.ts
  client/src/recoil/user/index.ts
  client/src/recoil/user/selector.ts
  client/src/types/task.d.ts
  yarn.lock
Labels: 🎯 환경설정, 😎 front-end, 🖋 리뷰요청, 🧐 refactor

#152 로드맵의 에픽 막대 드래그 앤 드랍 구현
  client/src/components/RoadmapBars/index.tsx
  client/src/components/RoadmapCalendar/index.tsx
  client/src/components/RoadmapItem/index.tsx
  client/src/lib/api/epic.ts
  client/src/lib/common/message/error.ts
  client/src/lib/common/message/success.ts
  client/src/lib/utils/date.ts
  client/src/lib/utils/epic.ts
  client/src/types/epic.ts
  server/src/Epics/Epics.controller.ts
Labels: 🎯 로드맵, 😎 front-end, 🖋 리뷰요청

#165 스토리 아이템 클릭 시 모달이 나타나고 내용은 API 호출이후에 받아온다.
  .eslintignore
  client/src/components/KanbanColumn/style.ts
  client/src/components/KanbanItem/index.tsx
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/KanbanModal/KanbanTask/style.ts
  client/src/components/KanbanModal/index.tsx
  client/src/components/KanbanModal/style.ts
  client/src/layers/Backlog/index.tsx
  client/src/styles/GlobalStyle.ts
  server/src/Stories/Stories.controller.ts
Labels: 🎯 칸반보드, 😎 front-end, 🖋 리뷰요청

#164 로드맵 페이지 인터랙션들에 소켓이벤트 등록
  .github/workflows/CI.yml
  client/src/components/RoadmapBars/index.tsx
  client/src/layers/Roadmap/index.tsx
  client/src/lib/api/epic.ts
  client/src/lib/utils/epic.ts
  client/src/pages/WorkPage/index.tsx
  client/src/types/epic.ts
  drop.sql
  init.sql
  server/socket.ts
  server/src/Epics/Epics.controller.ts
Labels: 🎯 로드맵, 😎 front-end, 😇 back-end, 🖋 리뷰요청

#163 프로젝트 카드 모달 구현
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/style.ts
  client/src/components/ProjectModal/index.tsx
  client/src/components/ProjectModal/style.ts
  client/src/components/TeamItemViewer/index.tsx
  client/src/components/index.ts
  client/src/layers/CoworkerStatus/index.tsx
  client/src/layers/GroupManagement/index.tsx
  client/src/layers/ProjectManagement/index.tsx
  client/src/lib/api/user.ts
  client/src/types/users.d.ts
  server/src/Users/Users.controller.ts
  server/src/Users/Users.router.ts
Labels: 😎 front-end, 😇 back-end, 🖋 리뷰요청, 🧐 refactor, 🎯 프로젝트 관리 페이지, 🎯 프로젝트 팀원 모달

#173 칸반에서 Task 추가 및 칸반 아이템 관련 버그 수정
  client/src/components/KanbanAddBtn/index.tsx
  client/src/components/KanbanColumn/index.tsx
  client/src/components/KanbanDeleteModal/index.tsx
  client/src/components/KanbanItem/index.tsx
  client/src/components/KanbanItem/style.ts
  client/src/components/KanbanItemInput/index.tsx
  client/src/components/KanbanItemInput/style.ts
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/KanbanModal/KanbanTask/style.ts
  client/src/components/KanbanModal/index.tsx
  client/src/contexts/epicContext.tsx
  client/src/lib/api/story.ts
  client/src/pages/WorkPage/index.tsx
  client/src/types/story.d.ts
  server/src/Stories/Stories.controller.ts
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end

#184 tsc가 작동하도록 tsconfig 변경 및 cluster 지원을 위한 adapter 설정
  client/src/Router.tsx
  client/src/lib/api/user.ts
  server/lib/config/corsConfig.ts
  server/lib/types/session.d.ts
  server/socket.ts
  server/src/Email/Email.controller.ts
  server/src/Email/Email.router.ts
  server/src/Epics/Epics.controller.ts
  server/src/Epics/Epics.router.ts
  server/src/Organizations/Organizations.controller.ts
  server/src/Organizations/Organizations.router.ts
  server/src/Projects/Projects.controller.ts
  server/src/Projects/Projects.router.ts
  server/src/Stories/Stories.controller.ts
  server/src/Stories/Stories.router.ts
  server/src/Tasks/Tasks.controller.ts
  server/src/Tasks/Tasks.router.ts
  server/src/Todo/Todo.controller.ts
  server/src/Todo/Todo.router.ts
  server/src/Users/Users.controller.ts
  server/src/Users/Users.router.ts
  server/src/utils/authValidator.ts
  server/src/utils/requestValidator.ts
  server/tsconfig.json
  yarn.lock
Labels: 😇 back-end

#185 프로젝트 모달에 필요한 각종 기능 추가 및 추가 기능 구현
  .github/workflows/CI.yml
  client/public/hyupup-logo.svg
  client/src/Router.tsx
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/style.ts
  client/src/components/ProjectModal/index.tsx
  client/src/components/ProjectModal/style.ts
  client/src/components/ProjectModalItem/index.tsx
  client/src/components/ProjectModalItem/style.ts
  client/src/components/SideBarDropdown/index.tsx
  client/src/layers/GroupManagement/index.tsx
  client/src/layers/Header/index.tsx
  client/src/layers/Header/style.ts
  client/src/layers/ProjectManagement/index.tsx
  client/src/lib/api/project.ts
  client/src/lib/api/user.ts
  client/src/lib/common/message/error.ts
  client/src/lib/common/message/index.ts
  client/src/lib/common/message/warning.ts
  client/src/lib/design/DropDown/index.tsx
  client/src/lib/design/Logo/index.tsx
  client/src/lib/design/Modal/index.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/LandingPage/style.ts
  client/src/pages/LogInPage/index.tsx
  server/src/Users/Users.controller.ts
  server/src/Users/Users.router.ts
  server/src/Users/Users.service.ts
Labels: 🎯 작업 페이지, 🎯 관리자 페이지, 😎 front-end, 😇 back-end, 🖋 리뷰요청, 🧐 refactor, 🎯 프로젝트 팀원 모달

#188 칸반보드 모달을 통해서 에픽 수정, 테스크 추가, 작업 인원 할당할 수 있다.
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/KanbanModal/KanbanTask/style.ts
  client/src/components/KanbanModal/index.tsx
  client/src/components/KanbanModal/style.ts
  client/src/lib/api/task.ts
  client/src/lib/common/message/error.ts
  client/src/lib/design/DropDown/index.tsx
  client/src/pages/WorkPage/index.tsx
  client/src/types/task.d.ts
  server/src/Tasks/Tasks.controller.ts
  server/src/Tasks/Tasks.router.ts
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end

#201 칸반 파일 구조 수정, 칸반 Unit Test 작성 및 Recoil로 일부 마이그레이션
  client/__test__/CustomRender.tsx
  client/jest.config.js
  client/package.json
  client/src/components/EpicPlaceholder/index.test.tsx
  client/src/components/KanbanColumn/KanbanAddBtn/index.tsx
  client/src/components/KanbanColumn/KanbanDeleteModal/index.tsx
  client/src/components/KanbanColumn/KanbanItem/index.tsx
  client/src/components/KanbanColumn/KanbanItem/style.ts
  client/src/components/KanbanColumn/KanbanItemInput/index.test.tsx
  client/src/components/KanbanColumn/KanbanItemInput/index.tsx
  client/src/components/KanbanColumn/KanbanItemInput/style.ts
  client/src/components/KanbanColumn/index.test.tsx
  client/src/components/KanbanColumn/index.tsx
  client/src/components/KanbanModal/KanbanTask/index.test.tsx
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/index.ts
  client/src/layers/Kanban/index.tsx
  client/src/lib/design/DropDown/index.tsx
  client/src/lib/hooks/useInput.tsx
  client/src/pages/WorkPage/index.tsx
  client/src/recoil/story/atom.ts
  client/src/recoil/story/selector.ts
  client/src/types/story.d.ts
  yarn.lock
Labels: 🎯 칸반보드, 😎 front-end

#224 리코일 마이그레이션, 칸반보드 및 테스크 소켓 통신, 칸반 모달 리펙토링, 칸반 모달 스토리 수정
  client/public/icons/modify.svg
  client/src/Router.tsx
  client/src/components/KanbanColumn/KanbanAddBtn/index.tsx
  client/src/components/KanbanColumn/KanbanAddBtn/style.ts
  client/src/components/KanbanColumn/KanbanDeleteModal/index.tsx
  client/src/components/KanbanColumn/KanbanItem/index.tsx
  client/src/components/KanbanColumn/KanbanItem/style.ts
  client/src/components/KanbanColumn/KanbanItemInput/index.tsx
  client/src/components/KanbanColumn/KanbanItemInput/style.ts
  client/src/components/KanbanColumn/index.tsx
  client/src/components/KanbanColumn/style.ts
  client/src/components/KanbanModal/KanbanModalTitle/index.tsx
  client/src/components/KanbanModal/KanbanModalTitle/style.ts
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/KanbanModal/KanbanTask/style.ts
  client/src/components/KanbanModal/index.tsx
  client/src/components/KanbanModal/style.ts
  client/src/components/ListViewHeader/index.tsx
  client/src/components/RoadmapBars/index.tsx
  client/src/layers/Backlog/index.tsx
  client/src/layers/CoworkerStatus/index.tsx
  client/src/layers/Kanban/index.tsx
  client/src/lib/api/story.ts
  client/src/lib/api/task.ts
  client/src/lib/common/message/success.ts
  client/src/lib/hooks/useInput.tsx
  client/src/lib/utils/story.ts
  client/src/pages/WorkPage/index.tsx
  client/src/recoil/story/index.ts
  client/src/recoil/story/selector.ts
  client/src/types/story.d.ts
  server/socket.ts
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end

#223 에픽 드래그 로직 리팩토링 및 성능개선
  client/public/icons/delete-icon-red.svg
  client/src/components/EpicEntryItem/index.tsx
  client/src/components/EpicEntryItem/style.ts
  client/src/components/RoadmapBars/index.tsx
  client/src/components/RoadmapBars/style.ts
  client/src/components/RoadmapCalendar/index.tsx
  client/src/components/RoadmapCalendar/style.ts
  client/src/components/RoadmapItem/index.tsx
  client/src/components/RoadmapItem/style.ts
  client/src/layers/Roadmap/index.tsx
  client/src/lib/common/message/error.ts
  server/socket.ts
Labels: 🎯 로드맵, 😎 front-end, 😱 bug, 🧐 refactor

#222 무한 스크롤 구현
  client/package.json
  client/src/Router.tsx
  client/src/components/ListViewItem/index.tsx
  client/src/components/LogInForm/index.tsx
  client/src/components/TodoInputBar/index.tsx
  client/src/layers/ListView/index.tsx
  client/src/lib/api/user.ts
  client/src/lib/design/Spinner/index.tsx
  client/src/lib/design/Spinner/style.ts
  client/src/pages/LogInPage/index.tsx
  client/src/pages/SignUpPage/index.tsx
  client/src/recoil/user/atom.ts
  client/src/recoil/user/index.ts
  client/src/recoil/user/selector.ts
  client/src/types/task.d.ts
  server/src/Users/Users.controller.ts
  server/src/Users/Users.router.ts
  server/src/Users/Users.service.ts
  yarn.lock
Labels: 🎯 홈페이지, 😎 front-end, 😇 back-end, 🖋 리뷰요청, 🧐 refactor
