Repository boostcampwm-2021/WEB23-HyupUp, pull requests merged in 2021-12, with the labels that each got.

#237 칸반 모달을 통한 테스크 삭제 및 사용자 할당 이슈 해결
  client/public/icons/modify.svg
  client/src/components/KanbanColumn/KanbanAddBtn/index.tsx
  client/src/components/KanbanColumn/KanbanDeleteModal/index.tsx
  client/src/components/KanbanColumn/KanbanItemInput/index.tsx
  client/src/components/KanbanColumn/KanbanItemInput/style.ts
  client/src/components/KanbanColumn/index.tsx
  client/src/components/KanbanColumn/style.ts
  client/src/components/KanbanModal/KanbanModalTitle/index.tsx
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/KanbanModal/KanbanTask/style.ts
  client/src/components/KanbanModal/TaskItemWithUser/index.tsx
  client/src/components/KanbanModal/TaskItemWithoutUser/index.tsx
  client/src/components/KanbanModal/index.tsx
  client/src/layers/Roadmap/index.tsx
  server/socket.ts
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end

#236 토스트 레이아웃 및 백엔드 테스트 코드
  client/src/App.tsx
  client/src/layers/ProjectManagement/index.tsx
  client/src/styles/GlobalStyle.ts
  init.sql
  server/src/Projects/Projects.controller.ts
  server/test/Projects.test.ts
  server/test/index.ts
Labels: 😎 front-end, 😇 back-end, 😱 bug, 🧐 refactor

#238 로드맵 페이지 버그수정
  client/src/components/EpicEntryItem/index.tsx
  client/src/components/EpicEntryItem/style.ts
  client/src/components/RoadmapBars/index.tsx
  client/src/components/RoadmapItem/index.tsx
  client/src/layers/Roadmap/index.tsx
  client/src/layers/Roadmap/style.ts
  client/src/lib/api/epic.ts
  client/src/pages/WorkPage/index.tsx
  mock.sql
  server/test/Epics.test.ts
Labels: 🎯 로드맵, 😎 front-end, 😱 bug

#255 test code의 mock 데이터를 다른 테스트와 일치
  server/test/Email.test.ts
  server/test/Todo.test.ts
  server/test/Users.test.ts
Labels: 🧐 refactor

#257 칸반 보드와 로드맵 실시간 통신 구현, 소켓과 관련된 훅과 서버 코드 수정
  client/src/Router.tsx
  client/src/components/EpicEntryItem/index.tsx
  client/src/components/KanbanColumn/KanbanAddBtn/index.tsx
  client/src/components/KanbanColumn/KanbanDeleteModal/index.tsx
  client/src/components/KanbanColumn/KanbanItem/index.tsx
  client/src/components/KanbanColumn/KanbanItemInput/index.tsx
  client/src/components/KanbanColumn/index.tsx
  client/src/components/KanbanModal/KanbanModalTitle/index.tsx
  client/src/components/KanbanModal/KanbanModalTitle/style.ts
  client/src/components/KanbanModal/KanbanTask/index.tsx
  client/src/components/KanbanModal/index.tsx
  client/src/components/Profile/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/components/RoadmapBars/index.tsx
  client/src/components/RoadmapItem/index.tsx
  client/src/components/SideBarDropdown/index.tsx
  client/src/layers/Kanban/index.tsx
  client/src/layers/Roadmap/index.tsx
  client/src/lib/api/task.ts
  client/src/lib/common/message/error.ts
  client/src/lib/hooks/index.ts
  client/src/lib/hooks/useSocketReceive.tsx
  client/src/lib/hooks/useSocketSend.tsx
  client/src/lib/hooks/useSocketSendUser.tsx
  client/src/pages/WorkPage/index.tsx
  init_1.sql
  server/socket.ts
  server/src/Stories/Stories.controller.ts
Labels: 🎯 칸반보드, 😎 front-end, 😇 back-end

#271 리스트 뷰가 비어 있을 경우 안내메시지 출력
  client/src/layers/ListView/index.tsx
  client/src/layers/ListView/style.ts
Labels: 🎯 홈페이지, 😎 front-end
